spring:

  application:
    name: dslist

  profiles:
    active: dev

  jpa:
    open-in-view: false

logging:
  level:
    root: INFO #DEBUG

cors:
  origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}
